services:
  wallos:
    container_name: wallos
    image: "bellamy/wallos:latest"
    expose:
      - "80"
    environment:
      - TZ='Asia/Taipei'
    volumes:
      - "db:/var/www/html/db"
      - "logos:/var/www/html/images/uploads/logos"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallos.rule=Host(`${WALLOS_DOMAIN}`)"
      - "traefik.http.routers.wallos.entrypoints=http"
volumes:
  db: {}
  logos: {}
