services:
  gateway:
    image: "traefik:v2.10"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/:/etc/traefik/:ro"
    ports:
      - "127.0.0.1:8888:80"
      - "127.0.0.1:8889:8080"
