global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  file:
    directory: "/etc/traefik"

log:
  level: INFO
  format: common

accessLog:
  format: common

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "172.22.0.1"