version: "3"
services:
  penta:
    hostname: penta
    build: ./penta
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.penta.rule=Host(`${domain}`) && PathPrefix(`/penta/`)"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
